require("plugins.plugins")

-- require("plugins.tokyonight")
require("core.options")
require("core.keymaps")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.nvim-tree")
require("plugins.bufferline")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.telescope")
